express = require('express')
app = express()
app.use express.static('.')
bodyParser = require('body-parser')
app.use bodyParser.json()
app.get '/', (req, res) ->
  res.sendFile __dirname + '/' + 'index4.html'
  return
app.listen 3000, ->
  console.log 'Example app listening on port 3000!'
  return

# ---
# generated by js2coffee 2.2.0